### ISSUE TITLE
AfnNetworking 3.1 can't use it

### ISSUE THREAD

**Issue by BulletTrain** [YouXianMing/Networking-Encapsulation#1]
Can you  fix it? Thanks.

**Comment by BulletTrain** [comment]
![](http://ww4.sinaimg.cn/large/79691b87jw1f6hig7fd0fj21kw10fas7.jpg)

**Comment by YouXianMing** [comment]
我不明白你的意思,你的意思是替换到最新的AFNetworking后就用不了了么?我刚刚试了下,都可以用.

**Comment by YouXianMing** [comment]
我知道你的意思了,我修改下

**Comment by YouXianMing** [comment]
已经提交并修改完毕.

**Comment by BulletTrain** [comment]
已经可以了，谢谢！感谢共享开源这个项目

**Comment by YouXianMing** [comment]
:)
